dist: trusty
group: stable
sudo: false
cache: bundler
language: ruby
addons:
  postgresql: '9.6'
  apt:
    packages:
      - graphviz
rvm:
  - 2.6.5
before_install:
  - gem install bundler
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - bundle install
  - bundle exec rake --version
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake spec
  - bundle exec rake yard
