group: stable
sudo: false
cache: bundler
language: ruby
addons:
  postgresql: '9.3'
  apt:
    packages:
      - graphviz
rvm:
  - 2.3.1
before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - bundle exec rake db:setup
before_install:
  - gem update bundler
script:
  - bundle exec rake spec
  - bundle exec rake yard
