# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29fa9d88d1cafa0ccbbff352bd96ea16575d519cfbc6dd47465c1c6aa54c7959bdd02ec0f193671c8619c98690ebc7c7f715ccfed0b94fe3396aa47f5b88dd40

test:
  secret_key_base: dc7b2dfb6ca8775a09290abaae58f69d6616985ab79cddbe2051affb479338f10a7182c3f80ed325fbed26b130a22ca5683ff92e31a9a884ab2460b4169f09a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
